### PR TITLE
Revamp polar coordinates system

### PR DESCRIPTION
**Pull request by marinight**
Created a polar coordinates struct + abstract, and changed all functions related to/using polar coordinates to use those types. Also added a `toPolar` function that converts from Cartesian coordinates to polar coordinates.

### CODE REVIEW

**Comment by marinight** [comment]
sorry about the random unrelated CONTRIBUTING change, lol

**Comment by kisetil** [comment]
Hi @marinight, thank you for your efforts. I'm a bit confused about the purpose of the PolarCoordinates structure in this context. Is it primarily a container?

For instance:

```Haxe
public static inline function pow(base:Complex, exponent:Float):Complex {
    var m = Complex.abs(base);
    var a = Complex.arg(base);

    var nM = Math.pow(m, exponent);
    var nA = a * exponent;

    // return Complex.fromPolar(nM, nA);
    return Complex.fromPolar(new PolarCoordinates(nM, nA));
}
```

It seems that `nM` and `nA` are already in polar form, so I'm not sure why the `PolarCoordinates` constructor is being used here. It appears somewhat inefficient, akin to using `exp(log(2))`.

Is there a specific reason for using `PolarCoordinates` in this case? Your clarification would be appreciated.
Thanks again for your help!

**Comment by marinight** [comment]
Yes, it is `PolarCoordinates` is just a container, kind of just for a ease of use to use Polar coordinates.
I just used an instance of `PolarCoordinates` as I changed `fromPolar` to take in a `PolarCoordinates` as an argument

**Comment by kisetil** [comment]
Thank you for your response, but I believe that in this context, creating a structure for handling polar numbers would introduce asymmetry, as there isn't an existing structure for managing complex numbers in rectangular form. After all, the class for handling complex numbers primarily uses rectangular coordinates, and adding a structure for polar numbers would likely complicate the class.

**Comment by marinight** [comment]
Fair enough

**Pull request closed without merging**
